name: publish-book

on: 

  workflow_dispatch:

env:
  NB_KERNEL: python
  NMA_REPO: course-content-dl
  NMA_MAIN_BRANCH: main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Get commit message
        run: |
          readonly local msg=$(git log -1 --pretty=format:"%s")
          echo "COMMIT_MESSAGE=$msg" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install CI tools
        run: |
          BRANCH=`python -c 'import os, re; m = re.search(r"nmaci:([\w-]+)", os.environ["COMMIT_MESSAGE"]); print("main" if m is None else m.group(1))'`
          wget https://github.com/NeuromatchAcademy/nmaci/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          sudo apt-get update
          sudo apt-get install -y --fix-missing
          sudo apt-get install -y xvfb ffmpeg
          pip install -r nmaci-$BRANCH/requirements.txt
          mv nmaci-$BRANCH/scripts/ ci/
          rm -r nmaci-$BRANCH
          rm -r $BRANCH.tar.gz
          echo ci/ >> .gitignore

      - name: Copy prereqs file
        run: |
          BRANCH=`python -c 'import os, re; m = re.search(r"course-content-dl:([\w-]+)", os.environ["COMMIT_MESSAGE"]); print("main" if m is None else m.group(1))'`
          wget https://github.com/NeuromatchAcademy/precourse/archive/refs/heads/$BRANCH.tar.gz
          tar -xzf $BRANCH.tar.gz
          mv precourse-$BRANCH/prereqs/ prereqs/
          rm -r precourse-$BRANCH
          rm -r $BRANCH.tar.gz

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter-book==0.10.2 ghp-import
          pip install jupyter_client==7.3.5  # downgrade jupyter-client to fix hangs

      - name: Build the book
        run: |
          python ci/generate_book_dl.py student
          ln -s ../tutorials book/tutorials
          ln -s ../projects book/projects
          ln -s ../prereqs book/prereqs
          jupyter-book build book
          python ci/parse_html_for_errors.py student

      - name: Commit book
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ghp-import -n -c "deeplearning.neuromatch.io" -m "Update course book" book/_build/html
          git checkout -f gh-pages
  
      - name: Publish to gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
